/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wca_app.view;

import java.util.List;
import javax.swing.JOptionPane;
import org.hibernate.Session;
import wca_app.model.Operator;
import wca_app.util.Autorization;
import wca_app.util.HibernateUtil;

/**
 *
 * @author Mata
 */
public class Loading extends javax.swing.JFrame {

    /**
     * Creates new form Loading
     */
    public Loading() {
        initComponents();
        new ConnectToDatabase().start();
    }

    private class ConnectToDatabase extends Thread {
        public void run(){
            Session s = HibernateUtil.getSession();
           
            List<Operator> lista = s.createQuery("From Operator").list();
            Operator operator = lista.isEmpty() ? null : lista.get(0);
            
                if (operator!=null && operator.getId() > 0) {
                    new AutorizationForm().setVisible(true);
                    dispose();
                } else {
                    JOptionPane.showMessageDialog(getRootPane(), "There is no" + 
                            " operator. Contact program developer");
                }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loadingImgLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));
        setUndecorated(true);
        setResizable(false);

        loadingImgLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wca_app/view/img/WCAlogo.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loadingImgLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loadingImgLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel loadingImgLbl;
    // End of variables declaration//GEN-END:variables
}
