/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wca_app.view;

import java.awt.Component;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.border.Border;
import wca_app.model.Operator;
import wca_app.view.Competition.CompetitionsPanel;
import wca_app.view.panel.CompetitorsPanel;
import wca_app.view.panel.ResultsPanel;
import wca_app.view.panel.ScramblesPanel;


public class MainView extends javax.swing.JFrame {
    
    private CompetitionsPanel competitionsPanel;
    private CompetitorsPanel competitorsPanel;
    private ResultsPanel resultsPanel;
    private ScramblesPanel scramblesPanel;
    private Operator operator;
    private Border loweredBorder = BorderFactory.createLoweredBevelBorder();
    private Border raisedBorder = BorderFactory.createRaisedBevelBorder();
    
    public MainView(Operator operator) {
        initComponents();
        this.operator = operator;
        if(operator.getIsAdmin() == true){
            setTitle("WCA - World Cube Association Admin");
        }else{
            setTitle("WCA - World Cube Association");
        }
        competitionsPanel = new CompetitionsPanel();
        competitorsPanel = new CompetitorsPanel();
        resultsPanel = new ResultsPanel();
        scramblesPanel = new ScramblesPanel();
        setPanel(competitionsPanel);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuPnl = new javax.swing.JPanel();
        icon = new javax.swing.JLabel();
        resultsBtn = new javax.swing.JButton();
        competitorsBtn = new javax.swing.JButton();
        scramblesBtn = new javax.swing.JButton();
        optionsBtn = new javax.swing.JButton();
        competitionsBtn = new javax.swing.JButton();
        decorativePnl = new javax.swing.JPanel();
        viewPnl = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/wca_app/view/img/small.png"))); // NOI18N

        resultsBtn.setText("Results");
        resultsBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        resultsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultsBtnActionPerformed(evt);
            }
        });

        competitorsBtn.setText("Competitors");
        competitorsBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        competitorsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                competitorsBtnActionPerformed(evt);
            }
        });

        scramblesBtn.setText("Scrambles");
        scramblesBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        scramblesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scramblesBtnActionPerformed(evt);
            }
        });

        optionsBtn.setText("Options");
        optionsBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        competitionsBtn.setText("Competitions");
        competitionsBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        competitionsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                competitionsBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout menuPnlLayout = new javax.swing.GroupLayout(menuPnl);
        menuPnl.setLayout(menuPnlLayout);
        menuPnlLayout.setHorizontalGroup(
            menuPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(menuPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(menuPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(icon, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(resultsBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(competitorsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(scramblesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(optionsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(competitionsBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        menuPnlLayout.setVerticalGroup(
            menuPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(icon)
                .addGap(18, 18, 18)
                .addComponent(competitionsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(resultsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(competitorsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(scramblesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(optionsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        decorativePnl.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout decorativePnlLayout = new javax.swing.GroupLayout(decorativePnl);
        decorativePnl.setLayout(decorativePnlLayout);
        decorativePnlLayout.setHorizontalGroup(
            decorativePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        decorativePnlLayout.setVerticalGroup(
            decorativePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout viewPnlLayout = new javax.swing.GroupLayout(viewPnl);
        viewPnl.setLayout(viewPnlLayout);
        viewPnlLayout.setHorizontalGroup(
            viewPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 825, Short.MAX_VALUE)
        );
        viewPnlLayout.setVerticalGroup(
            viewPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(menuPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(decorativePnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(viewPnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(decorativePnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void competitionsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_competitionsBtnActionPerformed
        setPanel(competitionsPanel);
    }//GEN-LAST:event_competitionsBtnActionPerformed

    private void resultsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultsBtnActionPerformed
        setPanel(resultsPanel);
    }//GEN-LAST:event_resultsBtnActionPerformed

    private void competitorsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_competitorsBtnActionPerformed
        setPanel(competitorsPanel);
    }//GEN-LAST:event_competitorsBtnActionPerformed

    private void scramblesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scramblesBtnActionPerformed
        setPanel(scramblesPanel);
    }//GEN-LAST:event_scramblesBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton competitionsBtn;
    private javax.swing.JButton competitorsBtn;
    private javax.swing.JPanel controlButtonPnl;
    private javax.swing.JPanel decorativePnl;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel icon;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel menuPnl;
    private javax.swing.JButton optionsBtn;
    private javax.swing.JButton resultsBtn;
    private javax.swing.JButton scramblesBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchField;
    private javax.swing.JButton updateBtn;
    private javax.swing.JPanel viewPnl;
    // End of variables declaration//GEN-END:variables

    public void setPanel(JPanel panel) {
        viewPnl.removeAll();
        viewPnl.add(panel);
        panel.setSize(viewPnl.getSize());
        viewPnl.revalidate();
        viewPnl.repaint();
        
        resetButtons();
        
        switch(panel.getName()){
            case "Competitions":
                competitionsBtn.setBorder(loweredBorder);
                break;
            case "Competitors":
                competitorsBtn.setBorder(loweredBorder);
                break;
            case "Results":
                resultsBtn.setBorder(loweredBorder);
                break;
            case "Scrambles":
                scramblesBtn.setBorder(loweredBorder);
                    
        }
        
        
        
    }

    private void resetButtons() {
        for (Component components : menuPnl.getComponents()) {
            if(components instanceof JButton){
                ((JButton) components).setBorder(raisedBorder);
            }
        }
    }
}
